### ISSUE TITLE
Prevent lazy loading fails on ReviseOperation

### ISSUE THREAD

**Issue by Rian190** [Laravel-Backpack/revise-operation#22]
I am trying to add prevent lazy loading in my app by using [PreventLazyLoading](https://laravel.com/docs/9.x/eloquent-relationships#preventing-lazy-loading). 

The ReviseOperation fails when loading the revision history. The root cause is a `foreach` loop in the [Search trait](https://github.com/Laravel-Backpack/CRUD/blob/main/src/app/Library/CrudPanel/Traits/Search.php#L393): 

Might this be something to rethink in the Backpack sourcecode? Or should I think about ignoring this specific case?

**Comment by Rian190** [comment]
Thank you for the quick response.

As reference for others; I have created this exception by the following code:

```
        Model::preventLazyLoading(! app()->isProduction() && !str_ends_with(request()->url(), 'search'));
```

No guaranty this will work in all backpack functionality.

**Comment by pxpm** [comment]
I've submitted #23 that should address this issue. 

I will be closing this issue report since we already have the fix, it should be merged soon. 

If you find other cases that we missed, please open a new issue report and we will take a look. 👀 

Thank you very much for raising this issue and providing the workaround 🙏 

Cheers
